CC=g++
CFlags=-std=gnu++2a -lpointing -L/usr/local/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

debug: main.cpp
	$(CC) $(CFlags) main.cpp -o main && ./main

